/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { AuthorsService } from './services/authors.service';
export { BooksService } from './services/books.service';
